export const ADD_POPULARS = 'ADD_POPULARS';
export const POPULARS_LOADING = 'POPULARS_LOADING';
export const POPULARS_FAILED = 'POPULARS_FAILED';

export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const PRODUCTS_FAILED = 'PRODUCTS_FAILED';

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const REMOVE_ALL_PRODUCTS_FROM_CART = 'REMOVE_ALL_PRODUCTS_FROM_CART';
export const ADD_PRODUCT_COST_TO_TOTAL = 'ADD_PRODUCT_COST_TO_TOTAL';

export const MARK_FAVORITE = 'MARK_FAVORITE';

export const ADD_ACCOUNT = 'ADD_ACCOUNT';
