export const ADD_POPULARS = 'ADD_POPULARS';
export const POPULARS_LOADING = 'POPULARS_LOADING';
export const POPULARS_FAILED = 'POPULARS_FAILED';

export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const PRODUCTS_FAILED = 'PRODUCTS_FAILED';