// export const PRODUCTS = [
//     { img: 'https://i.postimg.cc/mr41T347/salt.png', price: 3.87, name: "Salt", productId: 0, dishId: [2, 3,4, 5, 1]},
//     { img: 'https://i.postimg.cc/jdJDN3dz/chicken.jpg', price: 5.94, name: "Boneless Chicken", productId: 1, dishId: [1,8,4]},
//     { img: 'https://i.postimg.cc/Z5tCLPCX/pepper.jpg', price: 3.18, name: "Black pepper", productId: 2, dishId: [2, 3,4, 5, 1, 6, 8]},
//     { img: 'https://i.postimg.cc/W1GtYDZz/cheese.jpg', price: 1.84, name: "Swiss cheese", productId: 3, dishId: [1, 2, 3]},
//     { img: 'https://i.postimg.cc/FKhzM9bZ/ham.png', price: 3.97, name: "Cooked Ham", productId: 4, dishId: [1]},
//     { img: 'https://i.postimg.cc/YS80kJbw/bread-crumbs.jpg', price:8.00, name: "Bread crumbs", productId: 5, dishId: [2, 1]},
//     { img: 'https://i.postimg.cc/T153VhGR/salmon.jpg', price: 2.22, name: "Salmon", productId: 6, dishId: [2]},
//     { img: 'https://i.postimg.cc/Jtw4Pm4j/mustard.jpg', price: 1.97,name: "Mustard", productId: 7, dishId: [2, 7]},
//     { img: 'https://i.postimg.cc/xjBKWzX3/butter.jpg', price: 3.42,name: "Butter", productId: 8, dishId: [2]},
//     { img: 'https://i.postimg.cc/PxgmZjR7/eggs.jpg',price: 3.67, name: "Organic eggs", productId: 9, dishId: [3]},
//     { img: 'https://i.postimg.cc/tC283v95/rosemary.png',price: 0.99, name: "Rosemary", productId: 10, dishId: [3, 4, 5, 6, 7]},
//     { img: 'https://i.postimg.cc/pXfz43mf/lemon.jpg', price: 2.99, name: "Lemon", productId: 11, dishId: [2, 3, 4, 5, 6, 7, 8]},
//     { img: 'https://i.postimg.cc/jdJFGqTD/garlic.png', price: 2.45, name: "Garlic", productId: 12, dishId: [2, 3, 4]},
//     { img: 'https://i.postimg.cc/prkzSFdw/spaghetti.jpg',price: 1.67, name: "Spaghetti", productId: 13, dishId: [3]},
//     { img: 'https://i.postimg.cc/VsZ3cz7f/potato.jpg', price: 5.94,name: "Potato", productId: 14, dishId: [8]},
//     { img: 'https://i.postimg.cc/k5ypYC6d/cream.png', price: 1.87,name: "Cream", productsId:15, dishId: [8]},
//     { img: 'https://i.postimg.cc/tC283v95/rosemary.png',price: 0.99, name: "Vegetable oil",productId:16, dishId: [7,8]},
//     { img: 'https://i.postimg.cc/k4Pcqbx3/brown-rice.png', price: 2.45, name: "Sausages",productId:17, dishId: [7]},
//     { img: 'https://i.postimg.cc/6QTvgLT5/Buderim-Ginger-Original-Marmalade.jpg', price: 5.94,name: "Ginger marmalade",productsId:18, dishId: [7]},
//     { img: 'https://i.postimg.cc/76cKGZJw/carrot.jpg', price: 1.87,name: "Carrot", productId:19, dishId: [7, 6]},
//     { img: 'https://i.postimg.cc/6ptVjvdy/sausageproduct.png',price: 0.99, name: "Bacon", productId: 20, dishId: [7]},
//     { img: 'https://i.postimg.cc/R07t1bny/blackbeans.png', price: 5.94,name: "Black beans",productId: 21, dishId: [5,7, 6 ]},
//     { img: 'https://i.postimg.cc/k4Pcqbx3/brown-rice.png', price: 2.45, name: "Brown rice", productId: 22, dishId: [5, 6]},
// ]
export const PRODUCTS = [
    { img: 'https://i.postimg.cc/mr41T347/salt.png', price: 3.87, name: "Salt", productId: 0, dishId: [2, 3,4, 5, 1]},
    { img: 'https://i.postimg.cc/jdJDN3dz/chicken.jpg', price: 5.94, name: "Chicken", productId: 1, dishId: [1,8,4]},
    { img: 'https://i.postimg.cc/Z5tCLPCX/pepper.jpg', price: 3.18, name: "Black pepper", productId: 2, dishId: [2, 3,4, 5, 1, 6, 8]},
    { img: 'https://i.postimg.cc/W1GtYDZz/cheese.jpg', price: 1.84, name: "Swiss cheese", productId: 3, dishId: [1, 2, 3]},
    { img: 'https://i.postimg.cc/FKhzM9bZ/ham.png', price: 3.97, name: "Cooked Ham", productId: 4, dishId: [1]},
    { img: 'https://i.postimg.cc/YS80kJbw/bread-crumbs.jpg', price:8.00, name: "Bread crumbs", productId: 5, dishId: [2, 1]},
    { img: 'https://i.postimg.cc/T153VhGR/salmon.jpg', price: 2.22, name: "Salmon", productId: 6, dishId: [2]},
    { img: 'https://i.postimg.cc/Jtw4Pm4j/mustard.jpg', price: 1.97,name: "Mustard", productId: 7, dishId: [2, 7]},
    { img: 'https://i.postimg.cc/xjBKWzX3/butter.jpg', price: 3.42,name: "Butter", productId: 8, dishId: [2]},
    { img: 'https://i.postimg.cc/PxgmZjR7/eggs.jpg',price: 3.67, name: "Organic eggs", productId: 9, dishId: [3]},
    { img: 'https://i.postimg.cc/tC283v95/rosemary.png',price: 0.99, name: "Rosemary", productId: 10, dishId: [3, 4, 5, 6, 7]},
    { img: 'https://i.postimg.cc/pXfz43mf/lemon.jpg', price: 2.99, name: "Lemon", productId: 11, dishId: [2, 3, 4, 5, 6, 7, 8]},
    { img: 'https://i.postimg.cc/jdJFGqTD/garlic.png', price: 2.45, name: "Garlic", productId: 12, dishId: [2, 3, 4]},
    { img: 'https://i.postimg.cc/prkzSFdw/spaghetti.jpg',price: 1.67, name: "Spaghetti", productId: 13, dishId: [3]},
    { img: 'https://i.postimg.cc/VsZ3cz7f/potato.jpg', price: 5.94,name: "Potato", productId: 14, dishId: [8]},
    { img: 'https://i.postimg.cc/k5ypYC6d/cream.png', price: 1.87,name: "Cream", productsId:15, dishId: [8]},
    { img: 'https://i.postimg.cc/tC283v95/rosemary.png',price: 0.99, name: "Vegetable oil",productId:16, dishId: [7,8]},
    { img: 'https://i.postimg.cc/k4Pcqbx3/brown-rice.png', price: 2.45, name: "Sausages",productId:17, dishId: [7]},
    { img: 'https://i.postimg.cc/6QTvgLT5/Buderim-Ginger-Original-Marmalade.jpg', price: 5.94,name: "Ginger",productsId:18, dishId: [7]},
    { img: 'https://i.postimg.cc/76cKGZJw/carrot.jpg', price: 1.87,name: "Carrot", productId:19, dishId: [7, 6]},
    { img: 'https://i.postimg.cc/6ptVjvdy/sausageproduct.png',price: 0.99, name: "Bacon", productId: 20, dishId: [7]},
    { img: 'https://i.postimg.cc/R07t1bny/blackbeans.png', price: 5.94,name: "Black beans",productId: 21, dishId: [5,7, 6 ]},
    { img: 'https://i.postimg.cc/k4Pcqbx3/brown-rice.png', price: 2.45, name: "Brown rice", productId: 22, dishId: [5, 6]},
]